// Generated by scripts/css-module-types.mjs. Do not edit manually.
declare const styles: {
  readonly footer: string
  readonly main: string
  readonly progress: string
  readonly root: string
}

export default styles
