// Generated by scripts/css-module-types.mjs. Do not edit manually.
declare const styles: {
  readonly alignCenter: string
  readonly alignEnd: string
  readonly alignStart: string
  readonly alignStretch: string
  readonly gap2xl: string
  readonly gapL: string
  readonly gapM: string
  readonly gapNone: string
  readonly gapS: string
  readonly gapXl: string
  readonly gapXs: string
  readonly justifyBetween: string
  readonly justifyCenter: string
  readonly justifyEnd: string
  readonly justifyStart: string
  readonly root: string
  readonly row: string
  readonly wrap: string
}

export default styles
