// Generated by scripts/css-module-types.mjs. Do not edit manually.
declare const styles: {
  readonly body: string
  readonly close: string
  readonly footer: string
  readonly header: string
  readonly panel: string
  readonly root: string
  readonly sizeL: string
  readonly sizeM: string
  readonly sizeS: string
  readonly title: string
}

export default styles
