// Generated by scripts/css-module-types.mjs. Do not edit manually.
declare const styles: {
  readonly danger: string
  readonly ghost: string
  readonly primary: string
  readonly root: string
  readonly secondary: string
  readonly sizeL: string
  readonly sizeM: string
  readonly sizeS: string
  readonly spinner: string
}

export default styles
