// Generated by scripts/css-module-types.mjs. Do not edit manually.
declare const styles: {
  readonly form: string
  readonly lead: string
  readonly root: string
  readonly section: string
  readonly title: string
}

export default styles
