// Generated by scripts/css-module-types.mjs. Do not edit manually.
declare const styles: {
  readonly control: string
  readonly error: string
  readonly hint: string
  readonly label: string
  readonly root: string
  readonly textarea: string
}

export default styles
