// Generated by scripts/css-module-types.mjs. Do not edit manually.
declare const styles: {
  readonly default: string
  readonly narrow: string
  readonly root: string
  readonly wide: string
}

export default styles
