// Generated by scripts/css-module-types.mjs. Do not edit manually.
declare const styles: {
  readonly link: string
  readonly linkActive: string
  readonly logo: string
  readonly root: string
}

export default styles
