// Generated by scripts/css-module-types.mjs. Do not edit manually.
declare const styles: {
  readonly lead: string
  readonly link: string
  readonly root: string
  readonly title: string
}

export default styles
